### ISSUE TITLE
Please include the Smart LED Bulb Provisioning steps

### ISSUE THREAD

**Issue by truedat101** [nkaminski/csrmesh#2]
The instructions jump into control.  Should the user attempt to configure a mesh via the HomeBrite app?  Or will this cause the lightbulb to become unavailable?  Any additional information is helpful.  Also, please describe the limits of the support, for example, will GroupID destinations be possible, to send a command to a group of bulbs?

**Comment by nkaminski** [comment]
Sorry about the lack of documentation, thanks for the feedback and I will make sure to improve such :)

Currently only broadcasts are supported since I only have a single Feit AOM800/827/LED/HBR to test with but I will likely implement groups or individuals if I add more bulbs to my system. Please see response to your other issue regarding connection issues for a more detailed writeup.

**Comment by nkaminski** [comment]
Documentation updated.
